### ISSUE TITLE
Function to get listening sockets

### ISSUE THREAD

**Issue by MichaelRoberts98** [MichaelRoberts98/RedWatch#3]
A function that will return details on listening sockets. The tool may later analyze that list for known malicious processes although that will be another issue altogether.

**Comment by ChrisFischer-MTA** [comment]
This has been accomplished in part by firewall.py's socketscanning method used for quickgeneration and rapid firewall deployment.

**Comment by ChrisFischer-MTA** [comment]
Issue solved by threathunter.py
